# Generated by Django 6.0 on 2025-12-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rfps', to='rfp.vendor'),
        ),
    ]
